#!/usr/bin/env python

### Drawables ###

# Colors
DEFAULT_BACKGROUND_COLOR = "lightblue"
DEFAULT_FOREGROUND_COLOR = "black"
DEFAULT_HIGHLIGHT_COLOR = "red"

DEFAULT_POINT_COLOR = DEFAULT_FOREGROUND_COLOR
DEFAULT_LINE_COLOR = DEFAULT_FOREGROUND_COLOR
DEFAULT_LABEL_COLOR = DEFAULT_LINE_COLOR

# Attributes
DEFAULT_LINE_WIDTH = 2
DEFAULT_POINT_SIZE = 3  # Must be an odd number

### Modules ###

# Behavior
DEFAULT_SHOW_LABELS = True
DEFAULT_SPLIT_EVEN = True

# Padding
CANVAS_PADDING = 10
COORD_PADDING = 4
